---
ENV_DEV         : DEV
ENV_QA          : QA

GIT_URI_HTTPS   : https://github.com/anlt1988/concourse.git
GIT_URI_SSH     : git@github.com:anlt1988/concourse.git
GIT_BRANCH      : master

THIRD           : haha
