---

resources:
  - name: my-repo
    type: git
    source:
      uri: {{GIT_URI}}
      branch: {{GIT_BRANCH}}

jobs:
  - name: my-first-job
    public: true
    plan:
      - get: my-repo
      - task: first-task-of-the-first-job
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hey there!!!]

  - name: auto-job
    public: true
    plan:
      - get: my-repo
        trigger: true
      - task: an-auto-task
        file: my-repo/scripts/auto-task.yml
